### ISSUE TITLE
CMake build system for pronto

### ISSUE THREAD

**Issue by liesrock** [ipab-slmc/pronto-distro#25]
It would be nice if pronto would be built using CMake.
Is there any work towards this direction?

Thanks,
Luca Muratore

**Comment by mauricefallon** [comment]
can you describe what you would like to do? 

internally pronto does use CMake, with a minimal make script for invocation

**Comment by liesrock** [comment]
Thanks for your reply.

My main goal is to integrate pronto in our build system, called robotology-superbuild (https://github.com/robotology-playground/robotology-superbuild).

The robotology-superbuild works with project that can be built using CMake (not only internally).

Would it be possible to replace the minimal invocation make script, with a CMakeLists.txt?

**Comment by mauricefallon** [comment]
It should be certainly be possible for your to make your own fork and make these changes there very simply. is that not sufficient? (sorry to be obtuse)

**Comment by liesrock** [comment]
Thanks for your support (no worries about being obtuse).
