### ISSUE TITLE
failed to decode message signal-scope

### ISSUE THREAD

**Issue by mcamurri** [ipab-slmc/pronto-distro#34]
I'm experiencing for the first time the following a failure on signal-scope: 
It seems not to load properly the LCM definitions when started. When I start it, I get:
```
Traceback (most recent call last):
  File "<string>", line 30, in findLCMModules
  File "/home/fpolido/git/ipab-pronto-distro/build/lib/python2.7/dist-packages/bot_procman/__init__.py", line 12, in <module>
    from sheriff import Sheriff
  File "/home/fpolido/git/ipab-pronto-distro/build/lib/python2.7/dist-packages/bot_procman/sheriff.py", line 14, in <module>
    import lcm
  File "/usr/local/lib/python2.7/dist-packages/lcm/__init__.py", line 3, in <module>
    from ._lcm import LCM, LCMSubscription
ImportError: /usr/local/lib/python2.7/dist-packages/lcm/_lcm.so: undefined symbol: lcm_handle_timeout

Traceback (most recent call last):
  File "<string>", line 53, in findLCMModulesInSysPath
  File "<string>", line 35, in findLCMModules
UnboundLocalError: local variable 'module' referenced before assignment
```

I've tried bot to add the message definition path in the python file and in the `PYTHONPATH` in the `.bashrc`:
`export PYTHONPATH=$PYTHONPATH:$PRONTO_ROOT/build/lib/python2.7/dist-packages`

Tested with fresh clone on master branch.

@patmarion do you have a clue about why it is not loading the message definitions?

**Comment by patmarion** [comment]
The important error message in the text that you posted is here:

    ImportError: /usr/local/lib/python2.7/dist-packages/lcm/_lcm.so: undefined symbol: lcm_handle_timeout

lcm_handle_timeout is a symbol from the newer version of lcm.  So it looks like you might have multiple versions of lcm installed?  Or maybe you recently re-installed a different version?  Is it possible that signal-scope was compiled with one version of lcm, but at run-time it is loading a different version?  You could try running this command to find different lcm versions on your system:

    $ locate liblcm

And you can try testing which liblcm.so was used by signal-scope and which was used by the lcm python module you have installed to /usr/local by running these commands:

    $ ldd build/bin/signal-scope  | grep lcm
    $ ldd /usr/local/lib/python2.7/dist-packages/lcm/_lcm.so | grep lcm

Please post the output of all these commands, and also these:

    $ echo $PYTHONPATH
    $ echo $LD_LIBRARY_PATH

**Comment by mcamurri** [comment]
I think you are right. 

I have LCM 1.3.1 installed system wide and Pronto by default is using its internal version, the 1.0

Here's the output of `PYTHONPATH`:
`/home/fpolido/dls_ws/devel/lib/python2.7/dist-packages:/opt/ros/indigo/lib/python2.7/dist-packages:/home/fpolido/git/ipab-pronto-distro/build/lib/python2.7/dist-packages`
and `LD_LIBRARY_PATH`
`/home/fpolido/dls_ws/devel/lib:/home/fpolido/dls_ws/devel/lib/x86_64-linux-gnu:/opt/ros/indigo/lib/x86_64-linux-gnu:/opt/ros/indigo/lib:/usr/lib/x86_64-linux-gnu/gazebo-2.2/plugins:/home/fpolido/git/ipab-pronto-distro/build/lib/:/home/fpolido/git/ipab-pronto-distro/build/lib64/`

`ldd` commands:

`liblcm.so.1 => /home/fpolido/git/ipab-pronto-distro/build/lib/liblcm.so.1 (0x00007fcea1763000)`
`liblcm.so.1 => /home/fpolido/git/ipab-pronto-distro/build/lib/liblcm.so.1 (0x00007f66591bc000)`

I added `$PRONTO_ROOT` in front of build because signal-scope is built by pronto and placed there. The env variable is made by me to point to the pronto repo I want.

I try now to prevent pronto to build and install LCM 1.0, so it is forced to use the newer version.

Or uninstall LCM 1.3.1 systemwide.

**Comment by patmarion** [comment]
What if you add this at the beginning of the PYTHONPATH environment variable, and then run signal-scope:

    /home/fpolido/git/ipab-pronto-distro/build/lib/python2.7/site-packages

Does that directory contain an lcm folder?  (Note, site-packages, not dist-packages)

**Comment by mcamurri** [comment]
With site-packages it worked like a charm. Thanks a lot @patmarion.

Just to know, what it is contained in site packages? I'm not familiar with Python.

**Comment by patmarion** [comment]
When LCM is compiled and installed by pronto-distro, it installs two items:

  - the liblcm.so shared library, to build/lib
  - the lcm python module to build/lib/python2.7/site-packages

Without prepending your PYTHONPATH, at run time the python statement "import lcm" was resolving to the lcm python module that you have installed to /usr/local/lib/python2.7/dist-packages/lcm.  When that python module loads, it searches for the liblcm.so shared library.  Your custom LD_LIBRARY_PATH environment variable causes it to resolve liblcm.so to the copy installed under pront-distro build/lib.  So that is the mismatch.  Try tricky part here is that you had already customized your PYTHONPATH, but it turns out the the version of lcm installed by pront-distro installs to site-packages, not dist-packages.  Confusing!!

**Comment by mcamurri** [comment]
I don't know, but thanks for saving my day.
