### ISSUE TITLE
download command in frsm causing compile failure

### ISSUE THREAD

**Issue by mcamurri** [ipab-slmc/pronto-distro#39]
Hi,
the submodule frsm is forcing a download of an header file from a non-existent URL:

https://github.com/openhumanoids/frsm/blob/bbf1d83023ae35ecf595c93e46b8601206be9e9b/src/frsm-lcm/CMakeLists.txt#L11

this causes a fresh install of pronto-distro to fail at compilation time.

I suggest to include the header in the submodule, directly, or to look for a package dedicated to ConciseArgs.

I'm writing here because I can't raise issues on openhumanoids.

**Comment by mauricefallon** [comment]
This a very hacky way of retrieving that file which used to be hosted on googecode.

We've fixed it locally and use this branch:
https://github.com/openhumanoids/frsm/tree/mf-frsm-minor-mod

I've also made a pull request upstream to fix it there but the author hasn't responded
https://github.com/abachrach/frsm/pull/3

**Comment by mcamurri** [comment]
Ok. I've created a PR.
